- name: configure frontend server
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: Remove the default html directory of nginx
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create html directory of nginx to import frontend html
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: Download frontend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip   # by default ansible considers the source in ansible server
      dest: /usr/share/nginx/html
      remote_src: yes   # ansible looks for the source on remote server

  - name: Copy frontend.conf to /etc/nginx/default.d/
    ansible.builtin.copy:
      src: frontend.conf
      dest: /etc/nginx/default.d/frontend.conf

  - name: start and enable nginx service
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes